### PR TITLE
Fixed link in Ronak's bio

### LINKED ISSUE #31: Update Ronak's Bio to Hyperlink acmucsd.com
image

### PR DESCRIPTION
**Pull request by lisalluo**
Thought I would go ahead and fix the hyperlink since I was already doing stuff with the website :)

Resolves #31

### CODE REVIEW

File: src/data/BoardData.js [hunk 1]
```diff
@@ -16,7 +18,7 @@ const board = [
       "https://tesc-website.s3.us-east-2.amazonaws.com/board/vp-external-2020.jpg",
     email: "ronak@tesc.ucsd.edu",
     bio:
-      "Hello there! I'm a computer science major here at UCSD, and I'm the VP External for 2020-2021. When I'm not supporting our amazing sponsorship, design and marketing teams at TESC, I'm starting random side projects and cooking new recipes. I was previously the VP External for ACM at UC San Diego — check it out @ https://acmucsd.com",
+      <div>Hello there! I'm a computer science major here at UCSD, and I'm the VP External for 2020-2021. When I'm not supporting our amazing sponsorship, design and marketing teams at TESC, I'm starting random side projects and cooking new recipes. I was previously the VP External for ACM at UC San Diego — check it out @ <a href="https://acmucsd.com\" target="_blank">https://acmucsd.com</a>.</div>,
```
Comment (subhankar-panda) [inline src/data/BoardData.js:21]: doesn't need to be a div, can just be a `<>` (https://reactjs.org/docs/fragments.html). Not really an issue for this, just lyk for the future :)

Comment (lisalluo) [reply src/data/BoardData.js:21]: I didn't know that :o ty for the info

Comment (lisalluo) [reply src/data/BoardData.js]: oops also didn't catch the backslash so I removed that
